### PR TITLE
detach marketplace presenter onDestroy fragment

### LINKED ISSUE #235: NPE when click "Kin Balance" in MarketPlace
If you click "Kin Balance" quickly in MarketPlace when "Earn/Spend" is not displayed, kin will crash. Here  is the log:

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.kin.ecosystem.marketplace.view.SpendRecyclerAdapter.setEmptyView(android.view.View)' on a null object reference
        at com.kin.ecosystem.marketplace.view.MarketplaceFragment.setupEmptyItemView(MarketplaceFragment.java:125)
        at com.kin.ecosystem.marketplace.presenter.MarketplacePresenter.setupEmptyItemView(MarketplacePresenter.java:245)
        at com.kin.ecosystem.marketplace.presenter.MarketplacePresenter.access$100(MarketplacePresenter.java:43)
        at com.kin.ecosystem.marketplace.presenter.MarketplacePresenter$2.onResponse(MarketplacePresenter.java:230)
        at com.kin.ecosystem.marketplace.presenter.MarketplacePresenter$2.onResponse(MarketplacePresenter.java:227)
        at com.kin.ecosystem.core.data.offer.OfferRepository$2.onResponse(OfferRepository.java:78)
        at com.kin.ecosystem.core.data.offer.OfferRepository$2.onResponse(OfferRepository.java:73)
        at com.kin.ecosystem.core.data.offer.OfferRemoteData$1$2.run(OfferRemoteData.java:57)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

### PR DESCRIPTION
**Pull request by OrenZak**
#### Main purpose:
NPE while view is not in front and presenter didn't detached.
#### Technical description:
- moving onDetach for marketplace presenter into fragment onDestroy

Closes #235

### CODE REVIEW

File: sdk/src/main/java/com/kin/ecosystem/main/view/EcosystemActivity.java [hunk 1]
```diff
@@ -304,10 +303,6 @@ public void navigateBack() {
 
 	@Override
 	protected void onDestroy() {
-		if (marketplacePresenter != null) {
-			marketplacePresenter.onDetach();
-			marketplacePresenter = null;
```
Comment (YohayBar) [inline sdk/src/main/java/com/kin/ecosystem/main/view/EcosystemActivity.java:309]: you should still set marketplacePresenter = null

Comment (YohayBar) [reply sdk/src/main/java/com/kin/ecosystem/main/view/EcosystemActivity.java:309]: also can the same issue happen for ecosystemPresenter and balancePresenter?

**Review by YohayBar — APPROVED** [review]

**Comment by OrenZak** [comment]
Closes #235
